### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by chenxuhao** [wpybtw/Skywalker#2]
Hi,

I got an error like this:

$ ./build/skywalker --input ~/datasets/dist-inputs/orkut.gr 
orkut.gr
var: size_of_sample_lengths =  3
/jet/home/xhchen/work/Skywalker/include/sampler_result.cuh:269 ERROR: CUDA RT call "cudaPeekAtLastError()" failed with invalid device function (98).

Any idea?

Thanks!

**Comment by wpybtw** [comment]
Hi,

This repo was under active development these days. Please pull the recent commits and try it out.
Let me know if you find other problems.

Thanks

**Comment by chenxuhao** [comment]
> ./build/skywalker --input ~/datasets/dist-inputs/orkut.gr

Thanks. Now I got this error:

$ ./build/skywalker --input ~/datasets/galois-inputs/citeseer.gr 
citeseer.gr
generating random weight
/home/cxh/work/Skywalker/include/gpu_graph.cuh:124 ERROR: CUDA RT call "cudaMemAdvise(xadj, (vtx_num + 1) * sizeof(edge_t), cudaMemAdviseSetAccessedBy, device_id)" failed with invalid device ordinal (101).

**Comment by wpybtw** [comment]
Hi
This problem should be due to performing advice with the wrong GPU ID. 
This project now uses the first 'ngpu' GPUs by default.  If you wish to use other configurations, you might need to modify the code with the "cudaSetDevice" API in several positions.
